NUM_BANDS = 25
NUM_MINHASH_FUNCTIONS = 100
NUM_BUCKETS = 8000
NUM_BUCKET_SETS = 10
FRACTION_IMPORTANT_WORDS_THRESHOLD = 1
THRESHOLD_NUM_BUCKETS_PAIR_PRESENT = 3 * NUM_BUCKET_SETS
THRESHOLD_JACC_SIMILARITY = 0.2